//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gost()
        {
            this.Smjestaj = new HashSet<Smjestaj>();
        }
    
        public int MBR { get; set; }
        public string Adresa { get; set; }
        public string Kontakt { get; set; }
        public System.DateTime Datum_P { get; set; }
        public string Vrijeme_P { get; set; }
        public Nullable<int> RecepcijaBr_Rec { get; set; }
        public Nullable<int> RecepcijaHotelId_Hot { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Smjestaj> Smjestaj { get; set; }
        public virtual Recepcija Recepcija { get; set; }
    }
}
