//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recepcija
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recepcija()
        {
            this.Gosts = new HashSet<Gost>();
        }
    
        public int Br_Rec { get; set; }
        public string Lokal { get; set; }
        public string Mjesto_Rec { get; set; }
        public int HotelId_Hot { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual Recepcioner Recepcioner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gost> Gosts { get; set; }
    }
}
