//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Smjestaj
    {
        public int Id_Smjestaj { get; set; }
        public int GostMBR { get; set; }
        public int SobaBr_Sobe { get; set; }
        public int SobaHotelId_Hot { get; set; }
    
        public virtual Gost Gost { get; set; }
        public virtual Soba Soba { get; set; }
    }
}
